[package]
name = "somo"
version = "0.1.0"
authors = ["Euan Kemp <euank@euank.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
nix = "0.15.0"
libc = "0.2"
log = "0.4"
env_logger = "0.7.1"
